# Gradle Properties
org.gradle.jvmargs = -Xmx3G

# Source Options
# Use Modern Java(9+) Syntax (Courtesy of Jabel) - compiles to Java 8 bytecode
use_modern_java_syntax = true

# Compilation Options
generate_sources_jar = true
generate_javadocs_jar = false

# Testing
enable_junit_testing = true
show_testing_output = false

# Mod Information
mod_version = 3.2.0
root_package = com.builtbroken.atomic
mod_id = atomicscience
mod_name = Atomic Science

# Mod Metadata (Optional)
mod_description = Atomic science is a tech mod focused on nuclear physics. Featuring a mixture of reactors, processing systems, and useful machines. The main goal of the mod is to create a realistic system while building enjoyable gameplay.
mod_url = https://www.curseforge.com/minecraft/mc-mods/atomic-science
mod_update_json = https://forge.curseupdate.com/293507/atomicscience
# Delimit authors with commas
mod_authors = DarkCow aka DarkGuardsman
mod_credits = Calclavia - Original Author; Full credit list: https://github.com/BuiltBrokenModding/Atomic-Science/blob/1.12/README.md
mod_logo_path =

# Mapping Properties
mapping_channel = stable
mapping_version = 39
use_dependency_at_files = true

# Run Configurations
minecraft_username = Developer
extra_jvm_args =
extra_tweak_classes =

# Maven Publishing (Provide secret: MAVEN_USER, MAVEN_PASS)
publish_to_maven = false
publish_to_local_maven = false
maven_name = Atomic Science
maven_url =

# Publishing
# release_type can only be: release, beta or alpha
release_type = release
publish_with_changelog = ${{ it.file('CHANGELOG.md').exists() }}

# Publishing to CurseForge (Provide secret: CURSEFORGE_TOKEN)
publish_to_curseforge = false
curseforge_project_id =
curseforge_debug = false

# Publishing to Modrinth (Provide secret: MODRINTH_TOKEN)
publish_to_modrinth = false
modrinth_project_id =
modrinth_sync_readme = false
modrinth_debug = false

# Modify Minecraft Sources
change_minecraft_sources = false

# Tags
use_tags = true
tag_class_name = ${root_package}.Tags

# Access Transformers
use_access_transformer = false
access_transformer_locations = ${mod_id}_at.cfg

# Mixins
use_mixins = false
mixin_booter_version = 10.2
mixin_refmap = mixins.${mod_id}.refmap.json
mixin_package = ${root_package}.mixins
mixin_configs =
generate_mixins_json = false

# CoreMod
is_coremod = false
coremod_includes_mod = false
coremod_plugin_class_name =

# AssetMover
use_asset_mover = false
asset_mover_version = 2.5


